In [1]:
import numpy as np

a = np.array(['t', 'b', 'r', 'd', 'e', 'f', 'z', 'a'])
b = np.random.randint(1, 20, 8)

print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[ 1 11 10  3 18 11 14 13]


In [2]:
print(b > 10)

[False  True False False  True  True  True  True]


In [3]:
bool_arr = b > 10
print(bool_arr)
new_arr = b[bool_arr]
print(new_arr)

[False  True False False  True  True  True  True]
[11 18 11 14 13]


In [4]:
new_arr = b[b > 10]
new_arr

array([11, 18, 11, 14, 13])

In [5]:
new_arr = b[(b > 10) & (b < 18)]
new_arr

array([11, 11, 14, 13])

In [6]:
print(b)
c = b
c

[ 1 11 10  3 18 11 14 13]


array([ 1, 11, 10,  3, 18, 11, 14, 13])

In [7]:
c[:3] = 19
print(c)
c[c > 15] = 100
c

[19 19 19  3 18 11 14 13]


array([100, 100, 100,   3, 100,  11,  14,  13])

In [8]:
print(b)


[100 100 100   3 100  11  14  13]


In [9]:
print(b[b == 100])

[100 100 100 100]


In [10]:
ind = np.where(b == 100)
ind

(array([0, 1, 2, 4]),)

In [11]:
print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[100 100 100   3 100  11  14  13]


In [12]:
ind = np.where(b == 100)
print(ind)
print(a[ind])

(array([0, 1, 2, 4]),)
['t' 'b' 'r' 'e']
