In [1]:
import numpy as np

a = np.array(['t', 'b', 'r', 'd', 'e', 'f', 'z', 'a'])
b = np.random.randint(1, 20, 8)

print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[15 12  3  9 17  5  1  4]


In [2]:
print(b > 10)

[ True  True False False  True False False False]


In [3]:
bool_arr = b > 10
print(bool_arr)
new_arr = b[bool_arr]
print(new_arr)

[ True  True False False  True False False False]
[15 12 17]


In [4]:
new_arr = b[b > 10]
new_arr

array([15, 12, 17])

In [5]:
new_arr = b[(b > 10) & (b < 18)]
new_arr

array([15, 12, 17])

In [6]:
print(b)
c = b
c

[15 12  3  9 17  5  1  4]


array([15, 12,  3,  9, 17,  5,  1,  4])

In [7]:
c[:3] = 19
print(c)
c[c > 15] = 100
c

[19 19 19  9 17  5  1  4]


array([100, 100, 100,   9, 100,   5,   1,   4])

In [8]:
print(b)


[100 100 100   9 100   5   1   4]


In [9]:
print(b[b == 100])

[100 100 100 100]


In [10]:
ind = np.where(b == 100)
ind

(array([0, 1, 2, 4]),)

In [11]:
print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[100 100 100   9 100   5   1   4]


In [12]:
ind = np.where(b == 100)
print(ind)
print(a[ind])

(array([0, 1, 2, 4]),)
['t' 'b' 'r' 'e']


In [13]:
# np.reshape()
# np.resize()