In [1]:
import numpy as np

li = [1, 2, 3, 4, 5]
a = np.random.randint(1, 20, 5)
b = np.random.randint(1, 20, 5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[ 3  2 18  1 17]
[18  3 11 11  6]


In [2]:
li = [i+1 for i in li]
li

[2, 3, 4, 5, 6]

In [3]:
#increasing each elemnt by 1 using numpy
a = a + 1
a

array([ 4,  3, 19,  2, 18])

In [4]:
c = a + b
c

array([22,  6, 30, 13, 24])

In [5]:
d = a - b
d

array([-14,   0,   8,  -9,  12])

In [6]:
e = a * b
e

array([ 72,   9, 209,  22, 108])

In [7]:
f = a / b
f

array([0.22222222, 1.        , 1.72727273, 0.18181818, 3.        ])

In [8]:

g = a // b
g

array([0, 1, 1, 0, 3])

In [9]:
h = a ** b
h

array([    68719476736,              27, 116490258898219,            2048,
              34012224])

In [10]:
print(a)
# a.sum gives summ of all elements of array
print(a.sum())

# mean gives average
print(a.mean())
print(a.min())

# argmin() is used to find the index of minimum number
print(a.argmin())
print(a.max())
print(a.argmax())


[ 4  3 19  2 18]
46
9.2
2
3
19
2


In [11]:
print(a)
print(b)
a > b
a < b
a == b

# logical_or(and,not) are logical operators 

print(np.logical_or(a, b))
print(np.logical_and(a, b))

a[2] = 0
print(a)
print(np.logical_not(a))

[ 4  3 19  2 18]
[18  3 11 11  6]
[ True  True  True  True  True]
[ True  True  True  True  True]
[ 4  3  0  2 18]
[False False  True False False]
