**Indexing and Slicing**

In [1]:
import numpy as np
li=[1,2,3,4,5]
arr=np.array(li)
print(li)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [2]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)


(5,)
int64
(8,)


In [3]:
li_2d=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
print(li_2d)
arr=np.array(li_2d)
print(arr)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)


(4, 3)
int64
(24, 8)


In [5]:
print(li_2d[1][2])
print(arr[1][2])

# can also use indexing in this way in numpy
print(arr[1,2])

6
6
6


In [6]:
print(li_2d[1][:3])
print(arr[1][:3])
print(arr[1,:3])

[4, 5, 6]
[4 5 6]
[4 5 6]


In [7]:
#fixing column is not allowed in normal list
print(li_2d[0:3][2])

[7, 8, 9]


In [8]:
# fixing row as well as column is allowed in numpy
print(arr[:3,2])

[3 6 9]


In [9]:
# this is not posiible in normal list
print(arr[1:3,1:3])

[[5 6]
 [8 9]]


In [10]:
print(li_2d[1:3][1:3])

[[7, 8, 9]]
