In [1]:
import numpy as np

li = [1, 2, 3, 4, 5]
a = np.random.randint(1, 20, 5)
b = np.random.randint(1, 20, 5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[ 5  3  8 13  5]
[11 18 13 16 10]


In [2]:
li = [i+1 for i in li]
li

[2, 3, 4, 5, 6]

In [3]:
#increasing each elemnt by 1 using numpy
a = a + 1
a

array([ 6,  4,  9, 14,  6])

In [4]:
c = a + b
c

array([17, 22, 22, 30, 16])

In [5]:
d = a - b
d

array([ -5, -14,  -4,  -2,  -4])

In [6]:
e = a * b
e

array([ 66,  72, 117, 224,  60])

In [7]:
f = a / b
f

array([0.54545455, 0.22222222, 0.69230769, 0.875     , 0.6       ])

In [8]:

g = a // b
g

array([0, 0, 0, 0, 0])

In [9]:
h = a ** b
h

array([          362797056,         68719476736,       2541865828329,
       2177953337809371136,            60466176])

In [10]:
print(a)
# a.sum gives summ of all elements of array
print(a.sum())

# mean gives average
print(a.mean())
print(a.min())

# argmin() is used to find the index of minimum number
print(a.argmin())
print(a.max())
print(a.argmax())


[ 6  4  9 14  6]
39
7.8
4
1
14
3


In [11]:
print(a)
print(b)
a > b
a < b
a == b

# logical_or(and,not) are logical operators 

print(np.logical_or(a, b))
print(np.logical_and(a, b))

a[2] = 0
print(a)
print(np.logical_not(a))

[ 6  4  9 14  6]
[11 18 13 16 10]
[ True  True  True  True  True]
[ True  True  True  True  True]
[ 6  4  0 14  6]
[False False  True False False]
